# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='email',
            field=models.EmailField(default='', max_length=50, null=True, verbose_name='机房联系人邮件'),
        ),
    ]
