# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name="person's first name"),
        ),
        migrations.AddField(
            model_name='person',
            name='sec_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
