# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=10, unique=True, verbose_name='idc 简称')),
                ('idc_name', models.CharField(default='', max_length=50, verbose_name='idc 名字')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='idc phone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='idc email')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='idc 联系人')),
                ('remark', models.CharField(default='', max_length=100, verbose_name='remark')),
            ],
            options={
                'db_table': 'resources_idc',
            },
        ),
    ]
