# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, unique=True, verbose_name='字母简称')),
                ('idc_name', models.CharField(default='', max_length=128, verbose_name='中文名')),
                ('address', models.CharField(max_length=128, null=True, verbose_name='具体地址, 云厂商可以为空')),
                ('username', models.CharField(max_length=10, null=True, verbose_name='联系人')),
                ('user_phone', models.CharField(max_length=20, null=True, verbose_name='联系人电话')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='联系人Email')),
            ],
            options={
                'db_table': 'resources_idc',
            },
        ),
    ]
